### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by RyanDickson** [chrisgit/serverspec-custom_type#1]
Hi, I would like to use windows_task custom_type for a project I am involved in but cannot do so if the license is not specified. Thanks!

**Comment by chrisgit** [comment]
Hello @RyanDickson ,

Sorry for the delayed reply I've been away for a few days.

Thank you for pointing out that I have not included any licensing information, I do apologise and will add licensing details, my preference is to go with Unlicense or MIT. 

Feel free to update and improve the code, please do push any changes back.

Thanks again.

**Comment by chrisgit** [comment]
Added license (MIT) and Rspec tests.
